name: CI

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v7
    - name: Set up Python
      uses: actions/setup-python@v7
      with:
        python-version: "3.14"
    - name: Install Python dependencies
      run: pip install -r dev-requirements.txt
    - name: Lint
      run: ./scripts/lint.sh

  e2e-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v7
    - name: Set up Python
      uses: actions/setup-python@v7
      with:
        python-version: "3.14"
    - name: Install Python dependencies
      run: pip install -r dev-requirements.txt
    - name: Fetch containers
      run: docker compose build && docker compose pull
    - name: Run test
      run: ./scripts/test.sh
