name: CI

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v7
    - uses: actions/setup-go@v7
      with:
        go-version: "1.26"
    - name: Lint
      run: ./scripts/lint.sh

  e2e-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v7
    - uses: actions/setup-go@v7
      with:
        go-version: "1.26"
    - name: Unit tests
      run: go test ./...
    - name: Fetch containers
      run: docker compose build && docker compose pull
    - name: Run e2e test
      run: ./scripts/test.sh